= Developer's guide
:toc: left
:toclevels: 4
:icons: font
:rootdir: ../

== Build system

=== Maven

==== Build lifecycle

[NOTE]
Reference: link:https://maven.apache.org/ref/3.6.3/maven-core/lifecycles.html[]

. *clean*: deletes everything in `/target`
. *validate*
* checkstyle
. *generate-resources*
* asciidoctor
. *compile*: compiles code and copies resources to `/target/classes`
. *test*: runs unit tests
* spotbugs
* clirr
- Travis runs up to here
. *package*: creates build artifacts (.jar files) in `/target`
* javadoc
* source: creates source code jar
* license: downloads licenses
. *verify*
* pmd
. *install*: copies build artifacts into local maven repository
. *site*: not used
. *deploy*: copies build artifacts and maven meta files to `/snapshots` or `/releases`

==== Maven plugins

===== Checkstyle

[NOTE]
====
Runs goal link:https://maven.apache.org/plugins/maven-checkstyle-plugin/check-mojo.html[checkstyle:check] in *validate* phase
====

* Maven plugin version and checkstyle version in link:{rootdir}pom.xml[]
* Maven plugin configuration in link:{rootdir}vassal-app/pom.xml[]
* Checkstyle configuration in link:{rootdir}vassal-app/src/test/resources/checkstyle-checks.xml[]
* Exceptions from checks in link:{rootdir}vassal-app/src/test/resources/checkstyle-suppressions.xml[]

===== PMD

[NOTE]
====
Runs goal link:https://maven.apache.org/plugins/maven-pmd-plugin/check-mojo.html[pmd:check] in *verify* phase
====

* Maven plugin version in link:{rootdir}pom.xml[]
* Maven plugin configuration in link:{rootdir}vassal-app/pom.xml[]

===== Source

[NOTE]
====
Runs goal link:https://maven.apache.org/plugins/maven-source-plugin/jar-no-fork-mojo.html[source:jar-no-fork] in *package* phase
====

===== Javadoc

[NOTE]
====
Runs goal link:https://maven.apache.org/plugins/maven-javadoc-plugin/jar-mojo.html[javadoc:jar] in *package* phase
====

* Maven plugin version in link:{rootdir}pom.xml[]
* Maven plugin configuration in link:{rootdir}vassal-app/pom.xml[]

===== Spotbugs

[NOTE]
====
Runs goal link:https://spotbugs.github.io/spotbugs-maven-plugin/check-mojo.html[spotbugs:check] in *test* phase
====

* Maven plugin version in link:{rootdir}pom.xml[]
* Maven plugin configuration in link:{rootdir}vassal-app/pom.xml[]
* Spotbugs include filter configuration in link:{rootdir}vassal-app/src/test/resources/spotbugs-include-filter.xml[]

===== Clirr

[NOTE]
====
Runs goal link:https://www.mojohaus.org/clirr-maven-plugin/check-no-fork-mojo.html[clirr:check-no-fork] in *test* phase
====

* Maven plugin version in link:{rootdir}pom.xml[]
* Maven plugin configuration in link:{rootdir}vassal-app/pom.xml[]
* Configuration of ignores in link:{rootdir}vassal-app/src/test/resources/clirr-ignored-differences.xml[]

===== Asciidoc

[NOTE]
====
Runs goal link:https://asciidoctor.org/docs/asciidoctor-maven-plugin/[asciidoctor:process-asciidoc] in *generate-resources* phase
====

Asciidoc documentation:

* https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/
* https://asciidoctor.org/docs/user-manual/

The asciidoctor plugin runs once for each of the following:

. convert Reference Manual files to HTML
. convert Userguide to PDF
. convert Designer's Guide to PDF

[]
* Maven plugin version in link:{rootdir}pom.xml[]
* Maven plugin configuration in link:{rootdir}vassal-doc/pom.xml[]

===== License Maven Plugin

[NOTE]
====
Runs goal link:https://www.mojohaus.org/license-maven-plugin/aggregate-download-licenses-mojo.html[license:aggregate-download-licenses] in *package* phase
====

* Maven plugin version in link:{rootdir}pom.xml[]
* Maven plugin configuration in link:{rootdir}release-prepare/pom.xml[]

==== Build parameters

===== Version number

The internal version number (the one shown in the about screen) is set by the maven parameter `gitVersion` and defaults to the maven version number.
It is passed from the Makefile during the release process.

===== Skip parameters

Each build step can be skipped by passing certain parameters.

.Skipping build steps
|===
|Plugin|Skip parameter

|Main (Skip code compilation)
|`-Dmaven.main.skip=true`

|Surefire (Unit tests)
|`-DskipTests=true`

|Checkstyle
|`-Dcheckstyle.skip=true`

|Spotbugs
|`-Dspotbugs.skip=true`

|Javadoc
|`-Dmaven.javadoc.skip=true`

|Asciidoctor
|`-Dasciidoctor.skip=true`

|Clirr
|`-Dclirr.skip=true`

|License Maven Plugin
|`-Dlicense.skipAggregateDownloadLicenses=true`

|===

====== Examples
* Compile only, build jar in `vassal-app/target`, skip tests, checkstyle, spotbugs, javadoc, asciidoctor, clirr:

 $ mvn clean package -DskipTests=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Dmaven.javadoc.skip=true -Dasciidoctor.skip=true -Dclirr.skip=true

* Run AsciiDoctor only:

 $ mvn clean compile -Dmaven.main.skip=true -DskipTests=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Dmaven.javadoc.skip=true -Dclirr.skip=true


==== Regular TODOs

===== Check for new dependency versions

 $ mvn versions:display-dependency-updates

===== Check for maven plugin updates

 $ mvn versions:display-plugin-updates

==== Configuration of dependent projects

The project's public maven repository can be found at https://vassalengine.org/maven/

[source,xml]
.Example configuration for dependent projects:
----
<project>
  <dependencies>
    <dependency>
      <groupId>org.vassalengine</groupId>
      <artifactId>vassal-app</artifactId>
      <version>3.4.1</version> <!--1-->
    </dependency>
  </dependencies>
  <repositories>
    <repository>
      <id>vassal-releases</id>
      <url>https://vassalengine.org/maven/</url>
    </repository>
  </repositories>
</project>
----
<1> Use desired Vassal version here

==== Update release number in `pom.xml`

[source]
----
mvn version:set -DnewVersion=RELEASE -DgenerateBackupPoms=false
----
where RELEASE is the version to set.

=== make

.List of available make targets:
[source,makefile]
----
include::{rootdir}Makefile[lines=337]
----

== Release checklist

Steps to release version `x.y.z`

* [ ] Update the release announcement data `dist/notes/data.json` and Jinja templates in `dist/notes` with the changes for the new release.
* [ ] Fill in the release date in `CHANGES`.
* [ ] Add the new release to `dist/linux/org.vassalengine.vassal.metainfo.xml`.
* [ ] Clean clone

 $ make clean
 
* [ ] Propagate new version to `pom.xml` files:

 $ make version-set MAVEN_VERSION=x.y.z
 
* [ ] Commit the changes:

 $ git commit . -m "The x.y.z release"
 
* [ ] Tag current state as a release:

 $ git tag -s -m 'The x.y.z release.' x.y.z
 
* [ ] Push tag to origin and generate the release on GitHub

  $ git push --atomic origin HEAD x.y.z
  
* [ ] Update web-page 
** Update `util/current-release` and `util/current-beta` with release version number in `site` (`https://github.com/vassalengine/vassal-site`) repo and push to GitHub.
      (Note, this could be handled by an automatic PR from the GitHub release action).
** On `vassalengine.org`, pull `site-src` (`git@github.com:vassalengine/vassal-site-src.git`) repo

 $ cd ~/vassal-site-src
 $ git pull
 
** On `vassalengine.org`, pull `site` (`git@github.com:vassalengine/vassal-site.git`) repo

 $ cd /var/www/html/site
 $ git pull 

** Run script to update files in `releases`, Java documentation in `javadoc`, reference manual in `doc`, and Maven releases in `maven`.  Below, `TOKEN` can be either a GitHub personal access token or a file that contains such a token 

 $ ~/vassal-site-src/utils/update_from_release.sh --release x.y.z --token TOKEN Files JavaDoc ReferenceManual MavenReleases

* [ ] Update the release branch in `.github/workflows/package.yml`, if needed.
* [ ] Post release announcements 
** Download the **NOTES** artefact from the GitHub action of the release, and unpack:

 $ action_id=$(curl -L https://api.github.com/repos/vassalengine/vassal/actions/workflows/release.yml/runs | jq  '.workflow_runs[] | select(.head_branch=="x.y.z") | .id')
 $ url=$(curl -L https://api.github.com/repos/vassalengine/vassal/actions/runs/${action_id}/artifacts | jq -r '.artifacts[] | select(.name=="NOTES") | .archive_download_url')
 $ curl -L -H "Authorization: token ${token}" "${url}" -o NOTES.zip
 $ unzip NOTES.zip

** Alternatively, from a clone of the `site-src` repo, run (Below, `TOKEN` can be either a GitHub personal access token or a file that contains such a token)

 $ ~/vassal-site-src/utils/update_from_release.sh --release x.y.z --token TOKEN Notes
 
** Update the release notes in our forum: https://forum.vassalengine.org/t/vassal-X-Y-release-notes (Append content: `NOTES-news`)
** Our forum: https://forum.vassalengine.org/c/news/17 (Content: `NOTES-news`) Pin the new post, unpin the one for the previous release.
** BGG Computer Based Board Gaming forum: https://www.boardgamegeek.com/forum/28/bgg/computer-based-board-gaming (Content: `NOTES-bgg`)
** BGG Press Releases forum: https://www.boardgamegeek.com/forum/31/bgg/press-releases (Content: `NOTES-bgg`)
** Our forum at ConsimWorld: http://talk.consimworld.com/WebX/.ee6f15c/10067 (Content: `NOTES-csw`)
** VASL forum at GameSquad: http://www.gamesquad.com/forums/index.php?forums/vasl.103/ (Content: `NOTES-gh`)
** Facebook: Vassal Wargamers Americas: https://www.facebook.com/groups/vassalwargamers/ (Content: `NOTES-fb`)
** Facebook: Vassal Wargamers Europe: https://www.facebook.com/groups/VassalWargamersEurope (Content: `NOTES-fb`)
* [ ] Update FlatPak recipe 
** Clone

 $ git clone  git@github.com:flathub/org.vassalengine.vassal.git

** Alternatively, clone a fork of the above.
** Create a new branch

 $ cd org.vassalengine.vassal
 $ git checkout -b release-x.y.z
 
** Run script to update the recipe.  Below, `TOKEN` can be either a GitHub personal access token or a file that contains such a token 

 $ ./update_from_release.sh --release x.y.z --token TOKEN

** Commit changes

 $ git add org.vassalengine.vassal.yml maven-dependencies.yml
 $ git commit -m "Update for release x.y.z"

** Push commit to origin

 $ git push

** Create a pull request
* [ ] Merge pull request from GitHub release action named `Changes by create-pull-request action` to update `debian/changelog` and keep track of the release history. 
* [ ] Relax.

=== About release tags and workflows

When a tag is pushed to GitHub, the `release.yml` workflow will _automatically_ generate a release, and create a number artefacts for use in the release procedure.

* **JavaDoc** contains the Java API documentation
* **ReferenceManual** contains the Reference Manual
* **MavenReleases** contains the Maven repository entries
* **NOTES** contains the various release notes for different platforms
* **flatpak-recipe** contains updated reciepes for FlatHub
* **debian-source** contains the Debian source package files
* **rpm-source** contains the RPM source package

As part of the release workflow, the `debian/changelog` file is updated with the new release number and an appropriate message.  A pull request is automatically made against `master`.  This merge request should be merged to keep track of the release history in the `debian/changelog` file. 

== Running Vassal

=== Player

Main class: `VASSAL.launch.Player` +
VM arguments: `/path/to/module/VassalModule.vmod` or `VassalModule.vmod` if in current directory.

=== Editor

Main class: `VASSAL.launch.Editor` +
VM arguments: `--edit /path/to/module/VassalModule.vmod` or `VassalModule.vmod` if in current directory.

=== Additional parameters

* To simulate a HiDPI monitor: `-Dsun.java2d.uiScale=2`
