== VASSAL Reference Manual
[#top]

[.small]#<<index.adoc#toc,Home>> > *Module Extension*#

'''''

=== Module Extension

A Module Extension defines optional additional components to a Module.
Each extension is defined in its own file separate from the main Module file.
When playing, an extension is automatically loaded when its file is placed in the proper folder.
However, when editing, only the extension being edited is loaded.
In order to create a new extension or load an existing one for further editing, fist click "Load Module" in the "Extensions" section of the VASSAL start screen.
Select and open your .mod file.
For editing an existing extension file, click "Edit" in the "Extensions" section of the VASSAL start screen and select and open your extension .mdx file.
For creating an extension click "New" instead and save your work with a .mdx file ending.

Editing a Module Extension is done exactly like editing a Module, by adding and modifying components in the Configuration Window.
The only difference is that you cannot delete or modify components of the main Module while editing an extension.
Any components in an extension will always be added after those in the main Module.
See the User's Guide "Installation" page on loading extension files for play.

