= Prototype Definitions

Most games have counters that look different from one another, but behave very similarly. _Prototypes_ are a method of using templates to vastly simplify the definition of most Game Pieces. A Game Piece assigned a Prototype will inherit all of the Traits assigned to the Prototype.

You first define a Prototype as a set of Traits, and then use the set in the definition of other Game Pieces. A Game Piece can use any number of Prototypes.

For example, in the module _World War II_, we define a Prototype called Tank. The Tank Prototype includes these Traits: Mark When Moved, a Layer showing the tank with its regular strength and strength when damaged, and a Text Label allowing the owner to assign an ID number to the tank. Then, in the US pieces list, we create a counter for the Sherman tank, and in the German pieces list, we create one for the Tiger tank. Both of these pieces are assigned the Trait _Prototype – Tank_. Both Sherman and Tiger tank counters will include all the Traits from the Tank Prototype, without having to assign the Traits individually to each Tank counter.

It's strongly recommended that you use Prototypes whenever possible when creating Game Pieces, as module updates, revisions, and maintenance become considerably easier. When you decide to change or update the pieces in a module, updating the relevant Prototype will update all the pieces with that Prototype as a Trait, without having to individually update each piece.

For example, players of the World War II module described above complain that the font used in the Text Label Trait on the tanks is too small. Itʼs easy to edit the Tank Prototype to change the Text Label Trait to enlarge the font size from 9 points to 12. All pieces with the Tank Prototype will follow suit automatically, without having to update the pieces individually.

Pieces that use Prototype Traits can still have additional Traits defined to give them their own unique behavior.

*Defining a Prototype*

The process for defining a Prototype is just the same as for defining a Game Piece, but omits the Basic Piece Trait. Trait order applies to Prototypes in exactly the same way as for Game Pieces.

*To create a new Prototype Definition,*

. In the Configuration window, right-click the *[Game Piece Prototype Definitions]* node and pick *Add Definition.*
. In the *Prototype* dialog, select the Traits you wish to assign to the Prototype Definition, like you would for a Game Piece.
. Click *Ok*.

You can now assign the Prototype to Game Pieces or Cards by assigning them the Prototype trait, and specifying the new Prototype.

== Using Prototypes

* As with regular pieces, Traits in Prototypes are evaluated from bottom to top.
* Prototypes can include other Prototypes. Just assign the included Prototype as a Trait in the containing Prototype.
* You can use Prototypes to store any group of Traits that need to be re-used across multiple piece types as a block. For example, imagine a war game where there are both land and naval pieces. The naval pieces represent a variety of ships and submarines, all of which have common Traits: a Text Label Trait indicating the unitʼs speed, and a Delete Trait named Sink that removes the piece from the game. We could create a Prototype called Naval Unit that includes each of these Traits and assign the Prototype to all ship and submarine pieces.
* Pieces in At-Start Stacks, or that were created as part of the Replace with Other or Place Marker Traits, which use Prototypes will be updated if the Prototype definition is ever changed.
* Game Pieces that use Prototypes and are part of a saved game will not be updated if the Prototype definition is updated. As a result, a Prototype Definition can change in a later version of a module without invalidating saved games from previous versions. However, if you wish the pieces in the saved game to use the updated Prototype, you will need to run the Saved Game Updater in order to bring the pieces in a Saved Game up to date. See page 91 for more information.

== Pre-Setting Traits in a Prototype

If you want to pre-set pieces in a Game Piece Palette to start in a certain state, you can use key commands on them to change their state, and then save the module. (See page 40 for more information.)

== Prototype Definitions: Defining a Prototype

However, if the Game Pieces use Prototypes, the Game Piece Palette always loads with the default state of the Prototype. To resolve this, you can pre-set the state of a Trait in the Prototype Definition.

*To pre-set one or more Traits in a Prototype Definition,*

. In the *[Prototype Definitions]* node, right-click the Prototype Definition you wish to pre-set Traits for.
. In the *Properties* dialog, in the image preview window, right-click the piece image. From the Command Menu, select a Trait and adjust it as desired.

    If the Prototype does not include an image preview, you will need to expand the size of the *Properties* dialog in order to select the Command Menu. Right-click where the piece would be shown, in the white background area.

[arabic, start=3]
. Repeat Step 2 for each additional Trait you wish to pre-set.
. Click *Ok*.
