/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package bsh;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NONPRINTABLE = 6;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int HASH_BANG_COMMENT = 8;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int ABSTRACT = 10;
  /** RegularExpression Id. */
  int BOOLEAN = 11;
  /** RegularExpression Id. */
  int BREAK = 12;
  /** RegularExpression Id. */
  int CLASS = 13;
  /** RegularExpression Id. */
  int BYTE = 14;
  /** RegularExpression Id. */
  int CASE = 15;
  /** RegularExpression Id. */
  int CATCH = 16;
  /** RegularExpression Id. */
  int CHAR = 17;
  /** RegularExpression Id. */
  int CONST = 18;
  /** RegularExpression Id. */
  int CONTINUE = 19;
  /** RegularExpression Id. */
  int _DEFAULT = 20;
  /** RegularExpression Id. */
  int DO = 21;
  /** RegularExpression Id. */
  int DOUBLE = 22;
  /** RegularExpression Id. */
  int ELSE = 23;
  /** RegularExpression Id. */
  int ENUM = 24;
  /** RegularExpression Id. */
  int EXTENDS = 25;
  /** RegularExpression Id. */
  int FALSE = 26;
  /** RegularExpression Id. */
  int FINAL = 27;
  /** RegularExpression Id. */
  int FINALLY = 28;
  /** RegularExpression Id. */
  int FLOAT = 29;
  /** RegularExpression Id. */
  int FOR = 30;
  /** RegularExpression Id. */
  int GOTO = 31;
  /** RegularExpression Id. */
  int IF = 32;
  /** RegularExpression Id. */
  int IMPLEMENTS = 33;
  /** RegularExpression Id. */
  int IMPORT = 34;
  /** RegularExpression Id. */
  int INSTANCEOF = 35;
  /** RegularExpression Id. */
  int INT = 36;
  /** RegularExpression Id. */
  int INTERFACE = 37;
  /** RegularExpression Id. */
  int LONG = 38;
  /** RegularExpression Id. */
  int NATIVE = 39;
  /** RegularExpression Id. */
  int NEW = 40;
  /** RegularExpression Id. */
  int NULL = 41;
  /** RegularExpression Id. */
  int PACKAGE = 42;
  /** RegularExpression Id. */
  int PRIVATE = 43;
  /** RegularExpression Id. */
  int PROTECTED = 44;
  /** RegularExpression Id. */
  int PUBLIC = 45;
  /** RegularExpression Id. */
  int RETURN = 46;
  /** RegularExpression Id. */
  int SHORT = 47;
  /** RegularExpression Id. */
  int STATIC = 48;
  /** RegularExpression Id. */
  int STRICTFP = 49;
  /** RegularExpression Id. */
  int SWITCH = 50;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 51;
  /** RegularExpression Id. */
  int TRANSIENT = 52;
  /** RegularExpression Id. */
  int THROW = 53;
  /** RegularExpression Id. */
  int THROWS = 54;
  /** RegularExpression Id. */
  int TRUE = 55;
  /** RegularExpression Id. */
  int TRY = 56;
  /** RegularExpression Id. */
  int VOID = 57;
  /** RegularExpression Id. */
  int VOLATILE = 58;
  /** RegularExpression Id. */
  int WHILE = 59;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 60;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 61;
  /** RegularExpression Id. */
  int HEX_LITERAL = 62;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 63;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 64;
  /** RegularExpression Id. */
  int EXPONENT = 65;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 66;
  /** RegularExpression Id. */
  int STRING_LITERAL = 67;
  /** RegularExpression Id. */
  int LONG_STRING_LITERAL = 68;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 69;
  /** RegularExpression Id. */
  int IDENTIFIER = 70;
  /** RegularExpression Id. */
  int LETTER = 71;
  /** RegularExpression Id. */
  int DIGIT = 72;
  /** RegularExpression Id. */
  int LPAREN = 73;
  /** RegularExpression Id. */
  int RPAREN = 74;
  /** RegularExpression Id. */
  int LBRACE = 75;
  /** RegularExpression Id. */
  int RBRACE = 76;
  /** RegularExpression Id. */
  int LBRACKET = 77;
  /** RegularExpression Id. */
  int RBRACKET = 78;
  /** RegularExpression Id. */
  int SEMICOLON = 79;
  /** RegularExpression Id. */
  int COMMA = 80;
  /** RegularExpression Id. */
  int DOT = 81;
  /** RegularExpression Id. */
  int ASSIGN = 82;
  /** RegularExpression Id. */
  int GT = 83;
  /** RegularExpression Id. */
  int GTX = 84;
  /** RegularExpression Id. */
  int LT = 85;
  /** RegularExpression Id. */
  int LTX = 86;
  /** RegularExpression Id. */
  int BANG = 87;
  /** RegularExpression Id. */
  int TILDE = 88;
  /** RegularExpression Id. */
  int HOOK = 89;
  /** RegularExpression Id. */
  int COLON = 90;
  /** RegularExpression Id. */
  int EQ = 91;
  /** RegularExpression Id. */
  int LE = 92;
  /** RegularExpression Id. */
  int LEX = 93;
  /** RegularExpression Id. */
  int GE = 94;
  /** RegularExpression Id. */
  int GEX = 95;
  /** RegularExpression Id. */
  int NE = 96;
  /** RegularExpression Id. */
  int MATCH = 97;
  /** RegularExpression Id. */
  int NMATCH = 98;
  /** RegularExpression Id. */
  int BOOL_OR = 99;
  /** RegularExpression Id. */
  int BOOL_ORX = 100;
  /** RegularExpression Id. */
  int BOOL_AND = 101;
  /** RegularExpression Id. */
  int BOOL_ANDX = 102;
  /** RegularExpression Id. */
  int INCR = 103;
  /** RegularExpression Id. */
  int DECR = 104;
  /** RegularExpression Id. */
  int PLUS = 105;
  /** RegularExpression Id. */
  int MINUS = 106;
  /** RegularExpression Id. */
  int STAR = 107;
  /** RegularExpression Id. */
  int SLASH = 108;
  /** RegularExpression Id. */
  int BIT_AND = 109;
  /** RegularExpression Id. */
  int BIT_ANDX = 110;
  /** RegularExpression Id. */
  int BIT_OR = 111;
  /** RegularExpression Id. */
  int BIT_ORX = 112;
  /** RegularExpression Id. */
  int XOR = 113;
  /** RegularExpression Id. */
  int MOD = 114;
  /** RegularExpression Id. */
  int LSHIFT = 115;
  /** RegularExpression Id. */
  int LSHIFTX = 116;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 117;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTX = 118;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 119;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTX = 120;
  /** RegularExpression Id. */
  int PLUSASSIGN = 121;
  /** RegularExpression Id. */
  int MINUSASSIGN = 122;
  /** RegularExpression Id. */
  int STARASSIGN = 123;
  /** RegularExpression Id. */
  int SLASHASSIGN = 124;
  /** RegularExpression Id. */
  int ANDASSIGN = 125;
  /** RegularExpression Id. */
  int ANDASSIGNX = 126;
  /** RegularExpression Id. */
  int ORASSIGN = 127;
  /** RegularExpression Id. */
  int ORASSIGNX = 128;
  /** RegularExpression Id. */
  int XORASSIGN = 129;
  /** RegularExpression Id. */
  int MODASSIGN = 130;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 131;
  /** RegularExpression Id. */
  int LSHIFTASSIGNX = 132;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 133;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGNX = 134;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 135;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGNX = 136;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\n\"",
    "<NONPRINTABLE>",
    "<SINGLE_LINE_COMMENT>",
    "<HASH_BANG_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"class\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"transient\"",
    "\"throw\"",
    "\"throws\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<LONG_STRING_LITERAL>",
    "<FORMAL_COMMENT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"@gt\"",
    "\"<\"",
    "\"@lt\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\"@lteq\"",
    "\">=\"",
    "\"@gteq\"",
    "\"!=\"",
    "\"=~\"",
    "\"!~\"",
    "\"||\"",
    "\"@or\"",
    "\"&&\"",
    "\"@and\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"@bitwise_and\"",
    "\"|\"",
    "\"@bitwise_or\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"@left_shift\"",
    "\">>\"",
    "\"@right_shift\"",
    "\">>>\"",
    "\"@right_unsigned_shift\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"@and_assign\"",
    "\"|=\"",
    "\"@or_assign\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\"@left_shift_assign\"",
    "\">>=\"",
    "\"@right_shift_assign\"",
    "\">>>=\"",
    "\"@right_unsigned_shift_assign\"",
  };

}
