#
# Configure Metal Look'n'Feel for Dark theme
#
# Normal foregraound
primary1=0x1E1E1E
# Highlight foreground
primary2=0x3C3F41
# Other foreground
primary3=0x505050
# Normal background
secondary1=0x141414
# Highlight background
secondary2=0x2B2B2B
# Other background
secondary3=0x3C3F41
# Text color
text=0xBBBBBB
# Controls
control=0x3C3F41
# Background
background=0x2B2B2B

