#
# Configure Nimbus Look'n'Feel for Dark mode
#
control=0x2B2B2B
controlText=0xe6e6e6
info=0x2B2B2B
nimbusBase=0x121231
nimbusAlertYellow=0xf8bb00
nimbusDisabledText=0x808080
nimbusFocus=0x73a4d1
nimbusGreen=0xb0b332
nimbusInfoBlue=0x428bdd
nimbusLightBackground=0x121e31
nimbusOrange=0xbf6204
nimbusRed=0xa92e22
nimbusSelectedText=0xffffff
nimbusSelectionBackground=0x685d9c
text=0xe6e6e6
textInactiveText=gray
menu=0x2B2B2B
menuText=0xe6e6e6
#
# EOF
#
